# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Echo's Blog
baseurl:        ""
url:            "https://www.echo724.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Echo
  url:          https://www.echo724.github.io
  email:        eunchan1001@gmail.com
  github:       echo724
  facebook:     eunchan1001

# Custom vars
version:        
github:
  repo:         https://github.com/echo724/echo724.github.io
